[phases.setup]
nixPkgs = ["dotnet-sdk_10"]

[phases.build]
cmds = [
  "dotnet restore",
  "dotnet publish src/Excos.AspNetCore.Lite.TestServer/Excos.AspNetCore.Lite.TestServer.csproj -c Release -o out --no-restore"
]

[start]
cmd = "dotnet out/Excos.AspNetCore.Lite.TestServer.dll"

[variables]
ASPNETCORE_URLS = "http://0.0.0.0:8080"
ASPNETCORE_ENVIRONMENT = "Production"
