<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.FileProviders.Embedded" Version="10.0.0" />
    <PackageReference Include="Yarn.MSBuild" Version="1.22.19" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="wwwroot\**\*" />
  </ItemGroup>

  <Target Name="BuildClientApp" BeforeTargets="BeforeBuild">
    <Exec Command="yarn install --frozen-lockfile" WorkingDirectory="ClientApp" />
    <Exec Command="yarn build" WorkingDirectory="ClientApp" />
  </Target>

</Project>
