<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.FileProviders.Embedded" Version="10.0.0" />
    <PackageReference Include="Yarn.MSBuild" Version="1.22.19" />
  </ItemGroup>

  <Target Name="BuildClientApp" BeforeTargets="AssignTargetPaths">
    <Exec Command="yarn install --frozen-lockfile --network-timeout 100000" WorkingDirectory="ClientApp" />
    <Exec Command="yarn build" WorkingDirectory="ClientApp" />
    
    <!-- Add all wwwroot files to EmbeddedResource after they're created -->
    <ItemGroup>
      <EmbeddedResource Include="wwwroot\**\*" Exclude="wwwroot\app.js.map" Condition="'$(Configuration)' != 'Debug'" />
      <EmbeddedResource Include="wwwroot\**\*" Condition="'$(Configuration)' == 'Debug'" />
    </ItemGroup>
  </Target>

</Project>
